apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adaptive-app
  namespace: adaptive-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-uat
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"

spec:
  tls:
  - hosts:
    - www.adaptive-uxui.com  # or your custom domain
    secretName: adaptive-app-tls
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: www.adaptive-uxui.com
    http:
      paths:
      - backend:
          service:
            name: adaptive-app
            port:
              number: 80
        path: /
        pathType: Prefix