apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-uat2
spec:
  acme:
    email: hameed.goudat@dekra.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-uat2
    solvers:
    - http01:
        ingress:
          class: webapprouting.kubernetes.azure.com
